import 'dart:async';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_webrtc/flutter_webrtc.dart';
import 'webrtc_config.dart';

/// 🎧 PRODUCTION WebRTCAudioReceiver (PARENT app)
///
/// Creates WebRTC offer and receives audio stream from child.
///
/// Production improvements:
///  ✅ Centralized WebRTC config (shared with child app)
///  ✅ Proper state machine with callbacks
///  ✅ ICE candidate buffering (handles race conditions)
///  ✅ Uses docChanges instead of docs (avoids duplicate processing)
///  ✅ Connection timeout (30s) — fails fast
///  ✅ Proper resource disposal (no memory leaks)
///  ✅ Idempotent start/stop
///  ✅ Cleanup Firestore documents on stop
///  ✅ Audio level monitoring hook
class WebRTCAudioReceiver {
  static const String _tag = 'WebRTCReceiver';

  RTCPeerConnection? _peerConnection;
  MediaStream? _remoteStream;
  final RTCVideoRenderer renderer = RTCVideoRenderer();
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  bool _remoteSet = false;
  bool _rendererInitialized = false;
  bool _running = false;
  bool _disposed = false;
  String? _currentCallId;

  final List<RTCIceCandidate> _pendingCandidates = [];

  StreamSubscription? _callListener;
  StreamSubscription? _candidateListener;
  Timer? _connectionTimer;

  /// State change callback for UI updates
  void Function(WebRTCConnectionState state)? onStateChanged;

  /// ICE connection state callback
  void Function(RTCIceConnectionState state)? onIceConnectionState;

  /// Error callback
  void Function(String error)? onError;

  /// Whether receiver is currently running
  bool get isRunning => _running;

  /// Current call ID (null if not running)
  String? get currentCallId => _currentCallId;

  /// Remote audio stream (for UI playback / level monitoring)
  MediaStream? get remoteStream => _remoteStream;

  /// Start receiving audio stream from child
  ///
  /// [callId] — unique session ID generated by parent app
  Future<void> start(
    String callId, {
    void Function(RTCIceConnectionState)? onConnectionState,
  }) async {
    if (_running) {
      debugPrint('$_tag: Already running — stopping previous session');
      await stop();
    }

    _currentCallId = callId;
    _running = true;
    _disposed = false;
    _remoteSet = false;
    _pendingCandidates.clear();

    if (onConnectionState != null) {
      onIceConnectionState = onConnectionState;
    }

    _notifyState(WebRTCConnectionState.initializing);
    debugPrint('$_tag: Starting WebRTC for call $callId');

    try {
      // Step 1: Initialize renderer (needed for audio playback on Flutter)
      await renderer.initialize();
      _rendererInitialized = true;

      // Step 2: Clean up any stale signaling data from previous session
      // (defensive — if previous session crashed, leftover offer may exist)
      await _cleanupCallDocument(callId);

      // Step 3: Create peer connection with shared config
      _peerConnection = await createPeerConnection(
        WebRTCConfig.configuration,
      );

      _peerConnection!.onIceConnectionState = (state) {
        debugPrint('$_tag: ICE state = $state');
        onIceConnectionState?.call(state);
        _mapIceStateToConnectionState(state);
      };

      _peerConnection!.onIceGatheringState = (state) {
        debugPrint('$_tag: ICE gathering = $state');
      };

      _peerConnection!.onIceCandidate = (candidate) {
        _sendIceCandidate(candidate);
      };

      _peerConnection!.onTrack = (event) {
        debugPrint('$_tag: onTrack — streams=${event.streams.length}');
        if (event.streams.isNotEmpty) {
          _remoteStream = event.streams[0];
          renderer.srcObject = _remoteStream;
          debugPrint('$_tag: 🎧 Attached remote audio stream');
        }
      };

      _peerConnection!.onConnectionState = (state) {
        debugPrint('$_tag: PC state = $state');
      };

      // Step 4: Create offer
      _notifyState(WebRTCConnectionState.creatingOffer);
      final offer = await _peerConnection!.createOffer(
        WebRTCConfig.offerConstraints,
      );
      await _peerConnection!.setLocalDescription(offer);

      // Step 5: Persist offer to Firestore
      await _firestore
          .collection(WebRTCConfig.callsCollection)
          .doc(callId)
          .set({'offer': offer.toMap(), 'createdAt': FieldValue.serverTimestamp()});
      debugPrint('$_tag: 📤 Offer sent');

      // Step 6: Listen for child's answer
      _listenForAnswer(callId);

      // Step 7: Listen for child's ICE candidates
      _listenForCalleeCandidates(callId);

      // Step 8: Start connection timeout
      _startConnectionTimer();

      _notifyState(WebRTCConnectionState.waitingForAnswer);
    } catch (e, stackTrace) {
      debugPrint('$_tag: ❌ Start failed: $e');
      debugPrintStack(stackTrace: stackTrace);
      _running = false;
      _currentCallId = null;
      _notifyState(WebRTCConnectionState.failed);
      onError?.call('Failed to start: $e');
      await _cleanupResources();
    }
  }

  /// Stop receiving audio and clean up all resources
  Future<void> stop() async {
    if (!_running && _disposed) return;

    debugPrint('$_tag: Stopping WebRTC for call $_currentCallId');
    _running = false;
    _disposed = true;

    // Clean up Firestore signaling documents (defensive)
    if (_currentCallId != null) {
      await _cleanupCallDocument(_currentCallId!);
    }

    await _cleanupResources();
    _notifyState(WebRTCConnectionState.closed);
  }

  // ============ PRIVATE METHODS ============

  void _listenForAnswer(String callId) {
    _callListener = _firestore
        .collection(WebRTCConfig.callsCollection)
        .doc(callId)
        .snapshots()
        .listen(
      (snapshot) async {
        if (!snapshot.exists) return;
        final data = snapshot.data();
        if (data == null) return;

        if (data['answer'] != null && !_remoteSet) {
          debugPrint('$_tag: 📩 Received answer');
          await _handleAnswer(
            Map<String, dynamic>.from(data['answer']),
          );
        }
      },
      onError: (e) {
        debugPrint('$_tag: ❌ Answer listener error: $e');
        onError?.call('Signaling error: $e');
      },
    );
  }

  void _listenForCalleeCandidates(String callId) {
    _candidateListener = _firestore
        .collection(WebRTCConfig.callsCollection)
        .doc(callId)
        .collection(WebRTCConfig.calleeCandidatesSub)
        .snapshots()
        .listen(
      (snapshot) {
        // ✅ FIX: use docChanges to avoid reprocessing same candidates
        for (final change in snapshot.docChanges) {
          if (change.type != DocumentChangeType.added) continue;

          final data = change.doc.data();
          if (data == null) continue;

          final candidate = RTCIceCandidate(
            data['candidate'] as String?,
            data['sdpMid'] as String?,
            (data['sdpMLineIndex'] as num?)?.toInt(),
          );

          if (_remoteSet && _peerConnection != null) {
            try {
              _peerConnection!.addCandidate(candidate);
              debugPrint('$_tag: 📥 Added candidate (after answer)');
            } catch (e) {
              debugPrint('$_tag: ⚠️ Add candidate failed: $e');
            }
          } else {
            _pendingCandidates.add(candidate);
            debugPrint('$_tag: 📥 Buffered candidate (waiting for answer)');
          }
        }
      },
      onError: (e) {
        debugPrint('$_tag: ❌ Candidate listener error: $e');
      },
    );
  }

  Future<void> _handleAnswer(Map<String, dynamic> answerMap) async {
    if (_remoteSet || _peerConnection == null) return;

    try {
      final sdp = answerMap['sdp'] as String?;
      final type = answerMap['type'] as String?;
      if (sdp == null || type == null) {
        debugPrint('$_tag: ❌ Invalid answer — missing sdp/type');
        return;
      }

      await _peerConnection!.setRemoteDescription(
        RTCSessionDescription(sdp, type),
      );
      _remoteSet = true;
      debugPrint('$_tag: ✅ Remote description set');

      // Flush all buffered ICE candidates
      for (final candidate in _pendingCandidates) {
        try {
          _peerConnection?.addCandidate(candidate);
          debugPrint('$_tag: 📥 Flushed buffered candidate');
        } catch (e) {
          debugPrint('$_tag: ⚠️ Flush candidate failed: $e');
        }
      }
      _pendingCandidates.clear();

      _notifyState(WebRTCConnectionState.connecting);
    } catch (e, stackTrace) {
      debugPrint('$_tag: ❌ Handle answer failed: $e');
      debugPrintStack(stackTrace: stackTrace);
      onError?.call('Failed to handle answer: $e');
    }
  }

  Future<void> _sendIceCandidate(RTCIceCandidate candidate) async {
    if (_currentCallId == null) return;
    try {
      await _firestore
          .collection(WebRTCConfig.callsCollection)
          .doc(_currentCallId!)
          .collection(WebRTCConfig.callerCandidatesSub)
          .add(candidate.toMap());
      debugPrint('$_tag: 📤 Sent ICE candidate');
    } catch (e) {
      debugPrint('$_tag: ⚠️ Send ICE candidate failed: $e');
    }
  }

  void _startConnectionTimer() {
    _connectionTimer?.cancel();
    _connectionTimer = Timer(WebRTCConfig.connectionTimeout, () {
      if (!_remoteSet) {
        debugPrint('$_tag: ⏱️ Connection timeout — no answer from child');
        onError?.call('Connection timeout — child may be offline');
        _notifyState(WebRTCConnectionState.failed);
      }
    });
  }

  void _mapIceStateToConnectionState(RTCIceConnectionState state) {
    switch (state) {
      case RTCIceConnectionState.RTCIceConnectionStateNew:
      case RTCIceConnectionState.RTCIceConnectionStateChecking:
        _notifyState(WebRTCConnectionState.connecting);
        break;
      case RTCIceConnectionState.RTCIceConnectionStateConnected:
      case RTCIceConnectionState.RTCIceConnectionStateCompleted:
        _connectionTimer?.cancel();
        _notifyState(WebRTCConnectionState.connected);
        break;
      case RTCIceConnectionState.RTCIceConnectionStateFailed:
        _notifyState(WebRTCConnectionState.failed);
        break;
      case RTCIceConnectionState.RTCIceConnectionStateDisconnected:
        _notifyState(WebRTCConnectionState.disconnected);
        break;
      case RTCIceConnectionState.RTCIceConnectionStateClosed:
        _notifyState(WebRTCConnectionState.closed);
        break;
      case RTCIceConnectionState.RTCIceConnectionStateCount:
        // TODO: Handle this case.
        throw UnimplementedError();
    }
  }

  void _notifyState(WebRTCConnectionState state) {
    debugPrint('$_tag: State → ${state.label}');
    onStateChanged?.call(state);
  }

  Future<void> _cleanupCallDocument(String callId) async {
    try {
      // Delete all sub-collections first, then the document
      final batch = _firestore.batch();

      final callerCandidates = await _firestore
          .collection(WebRTCConfig.callsCollection)
          .doc(callId)
          .collection(WebRTCConfig.callerCandidatesSub)
          .get();
      for (final doc in callerCandidates.docs) {
        batch.delete(doc.reference);
      }

      final calleeCandidates = await _firestore
          .collection(WebRTCConfig.callsCollection)
          .doc(callId)
          .collection(WebRTCConfig.calleeCandidatesSub)
          .get();
      for (final doc in calleeCandidates.docs) {
        batch.delete(doc.reference);
      }

      // Delete main document
      batch.delete(_firestore.collection(WebRTCConfig.callsCollection).doc(callId));

      await batch.commit();
      debugPrint('$_tag: 🧹 Cleaned up call document $callId');
    } catch (e) {
      debugPrint('$_tag: ⚠️ Cleanup failed (non-fatal): $e');
    }
  }

  Future<void> _cleanupResources() async {
    _connectionTimer?.cancel();
    _connectionTimer = null;

    await _callListener?.cancel();
    _callListener = null;

    await _candidateListener?.cancel();
    _candidateListener = null;

    _pendingCandidates.clear();
    _remoteSet = false;

    try {
      if (_rendererInitialized) {
        await renderer.srcObject?.dispose();
        renderer.srcObject = null;
        await renderer.dispose();
        _rendererInitialized = false;
      }
    } catch (e) {
      debugPrint('$_tag: Renderer dispose error: $e');
    }

    try {
      await _peerConnection?.close();
    } catch (e) {
      debugPrint('$_tag: PC close error: $e');
    }
    _peerConnection = null;
    _remoteStream = null;
    _currentCallId = null;
  }
}
