import 'package:cloud_firestore/cloud_firestore.dart';

import '../../models/child_live_data_model.dart';


/// 🔄 ChildDataRepository — Firestore operations for child_live_data + child_control
///
/// Responsibilities:
///  - Listen to real-time child_live_data updates
///  - Send sync_request to child
///  - Listen to child_control for sync_mic state
class ChildDataRepository {
  static const _liveDataCollection = 'child_live_data';
  static const _controlCollection = 'child_control';

  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  /// Stream child's live data (real-time updates)
  Stream<ChildLiveDataModel?> streamChildLiveData(String childUid) {
    return _firestore
        .collection(_liveDataCollection)
        .doc(childUid)
        .snapshots()
        .map((snapshot) {
      if (!snapshot.exists || snapshot.data() == null) return null;
      return ChildLiveDataModel.fromFirestore(
        Map<String, dynamic>.from(snapshot.data()!),
      );
    });
  }

  /// Get child's live data (one-time fetch)
  Future<ChildLiveDataModel?> getChildLiveData(String childUid) async {
    final snapshot =
        await _firestore.collection(_liveDataCollection).doc(childUid).get();
    if (!snapshot.exists || snapshot.data() == null) return null;
    return ChildLiveDataModel.fromFirestore(
      Map<String, dynamic>.from(snapshot.data()!),
    );
  }

  /// Send sync_request to child (parent wants fresh data now)
  Future<void> requestSync(String childUid) async {
    await _firestore.collection(_controlCollection).doc(childUid).set({
      'sync_request': true,
      'requested_at': FieldValue.serverTimestamp(),
    }, SetOptions(merge: true));
  }

  /// Stop sync_request (clear flag)
  Future<void> clearSyncRequest(String childUid) async {
    await _firestore.collection(_controlCollection).doc(childUid).set({
      'sync_request': false,
      'last_sync': FieldValue.serverTimestamp(),
    }, SetOptions(merge: true));
  }

  /// Start mic listening on child
  /// [callId] is the WebRTC session ID generated by parent
  Future<void> startMicListening(String childUid, String callId) async {
    await _firestore.collection(_controlCollection).doc(childUid).set({
      'sync_mic': true,
      'call_id': callId,
      'listening_started_at': FieldValue.serverTimestamp(),
      'listening_initiated_by': 'parent',
    }, SetOptions(merge: true));
  }

  /// Stop mic listening on child
  Future<void> stopMicListening(String childUid) async {
    await _firestore.collection(_controlCollection).doc(childUid).set({
      'sync_mic': false,
      'call_id': FieldValue.delete(),
      'listening_stopped_at': FieldValue.serverTimestamp(),
    }, SetOptions(merge: true));
  }

  /// Stream child_control document (for monitoring sync_mic state)
  Stream<Map<String, dynamic>?> streamChildControl(String childUid) {
    return _firestore
        .collection(_controlCollection)
        .doc(childUid)
        .snapshots()
        .map((snapshot) {
      if (!snapshot.exists || snapshot.data() == null) return null;
      return Map<String, dynamic>.from(snapshot.data()!);
    });
  }
}
